version: '3.5'
services:
    db:
      container_name: db_desafio_nodejs_2022_1
      image: mongo
      command: mongod --quiet --logpath /dev/null
      ports: 
          - 27017:27017

    api:
        depends_on:
            - db
        volumes: 
            - ./:/app
            - ./node_modules:/app/node_modules
        container_name: desafio_nodejs_2022_1
        environment:
            - DATABASE_URL=mongodb://db/desafio_nodejs_2022_1
        build:
            context: ./
        ports:
            - "5000:5000"
        command: yarn start